_wandb:
    value:
        cli_version: 0.22.2
        e:
            fse2dih7fz1ak210nli9x31py8qt7b2u:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "15032385536"
                codePath: nlp_8k.ipynb
                codePathLocal: nlp_8k.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "459987656704"
                email: william.jallot@epfl.ch
                executable: /opt/homebrew/Caskroom/miniconda/base/envs/asset_pricing/bin/python
                git:
                    commit: 89ab87fd6d128312a7bc2fdf5b0a9bab9b13a937
                    remote: https://github.com/Wfiles/news-based-asset-pricing
                host: tsf-476-wpa-0-046.epfl.ch
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit
                program: /Users/williamjallot/Desktop/semester_project/news-based-asset-pricing/nlp_8k.ipynb
                python: CPython 3.12.8
                root: /Users/williamjallot/Desktop/semester_project/news-based-asset-pricing
                startedAt: "2025-12-04T14:56:59.971534Z"
                writerId: fse2dih7fz1ak210nli9x31py8qt7b2u
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 105
            "3":
                - 2
            "4": 3.12.8
            "5": 0.22.2
            "6": 4.56.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
